-- =====================================================================================
-- SAP S/4HANA Data Products - Complete DDL Export
-- =====================================================================================
-- This file contains all CREATE DATABASE and CREATE TABLE statements for the three
-- SAP S/4HANA data products: Sales Order, Customer, and Shipping Point
-- =====================================================================================
-- Generated on: $(date)
-- =====================================================================================

-- =====================================================================================
-- DATABASE CREATE STATEMENTS
-- =====================================================================================

-- Create Sales Order Database
CREATE DATABASE IF NOT EXISTS SAP_DATA_PRODUCT_SALES_ORDER 
COMMENT = 'SAP S/4HANA Sales Order Data Product - Complete sales order processing data with header, items, and master data relationships';

-- Create Customer Database  
CREATE DATABASE IF NOT EXISTS SAP_DATA_PRODUCT_CUSTOMER 
COMMENT = 'SAP S/4HANA Customer Data Product - Customer master data with organizational structure and multilingual support';

-- Create Shipping Point Database
CREATE DATABASE IF NOT EXISTS SAP_DATA_PRODUCT_SSP 
COMMENT = 'SAP S/4HANA Shipping Point Data Product - Shipping point master data with plant relationships and multilingual descriptions';

-- =====================================================================================
-- CUSTOMER DATABASE TABLES
-- =====================================================================================

USE DATABASE SAP_DATA_PRODUCT_CUSTOMER;
USE SCHEMA PUBLIC;

-- Country Table
CREATE OR REPLACE TABLE COUNTRY_TABLE (
    COUNTRY VARCHAR(3) NOT NULL,
    COUNTRY_NAME VARCHAR(50) NOT NULL,
    REGION VARCHAR(3),
    CURRENCY VARCHAR(5),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COUNTRY)
);

-- Customer Address Table
CREATE OR REPLACE TABLE CUSTOMER_ADDRESS_TABLE (
    CUSTOMER VARCHAR(10) NOT NULL,
    ADDRESS_TYPE VARCHAR(2) NOT NULL,
    ADDRESS_NUMBER VARCHAR(10) NOT NULL,
    STREET VARCHAR(60),
    CITY VARCHAR(35),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(3),
    REGION VARCHAR(3),
    TELEPHONE VARCHAR(16),
    EMAIL VARCHAR(241),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER, ADDRESS_TYPE, ADDRESS_NUMBER)
);

-- Customer Contact Table
CREATE OR REPLACE TABLE CUSTOMER_CONTACT_TABLE (
    CUSTOMER VARCHAR(10) NOT NULL,
    CONTACT_PERSON VARCHAR(30) NOT NULL,
    CONTACT_ROLE VARCHAR(2),
    TELEPHONE VARCHAR(16),
    EMAIL VARCHAR(241),
    DEPARTMENT VARCHAR(40),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER, CONTACT_PERSON)
);

-- Customer Group Table
CREATE OR REPLACE TABLE CUSTOMER_GROUP_TABLE (
    CUSTOMER_GROUP VARCHAR(2) NOT NULL,
    CUSTOMER_GROUP_NAME VARCHAR(20) NOT NULL,
    CUSTOMER_GROUP_DESCRIPTION VARCHAR(40),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_GROUP)
);

-- Customer Master Table
CREATE OR REPLACE TABLE CUSTOMER_MASTER_TABLE (
    CUSTOMER VARCHAR(10) NOT NULL,
    CUSTOMER_NAME VARCHAR(35) NOT NULL,
    CITY VARCHAR(35),
    COUNTRY VARCHAR(3),
    POSTAL_CODE VARCHAR(10),
    STREET VARCHAR(60),
    REGION VARCHAR(3),
    CUSTOMER_GROUP VARCHAR(2) NOT NULL,
    SALES_ORGANIZATION VARCHAR(4) NOT NULL,
    DISTRIBUTION_CHANNEL VARCHAR(2) NOT NULL,
    DIVISION VARCHAR(2) NOT NULL,
    CUSTOMER_STATUS VARCHAR(1) NOT NULL,
    CUSTOMER_TYPE VARCHAR(2),
    INDUSTRY_SECTOR VARCHAR(4),
    TAX_NUMBER VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER)
);

-- Distribution Channel Table
CREATE OR REPLACE TABLE DISTRIBUTION_CHANNEL_TABLE (
    DISTRIBUTION_CHANNEL VARCHAR(2) NOT NULL,
    DISTRIBUTION_CHANNEL_NAME VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DISTRIBUTION_CHANNEL)
);

-- Division Table
CREATE OR REPLACE TABLE DIVISION_TABLE (
    DIVISION VARCHAR(2) NOT NULL,
    DIVISION_NAME VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DIVISION)
);

-- Region Table
CREATE OR REPLACE TABLE REGION_TABLE (
    REGION VARCHAR(3) NOT NULL,
    REGION_NAME VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(3) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REGION)
);

-- Sales Organization Table
CREATE OR REPLACE TABLE SALES_ORGANIZATION_TABLE (
    SALES_ORGANIZATION VARCHAR(4) NOT NULL,
    SALES_ORGANIZATION_NAME VARCHAR(20) NOT NULL,
    COMPANY_CODE VARCHAR(4) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SALES_ORGANIZATION)
);

ALTER TABLE CUSTOMER_ADDRESS_TABLE
ADD CONSTRAINT FK_CUSTOMER_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.CUSTOMER_MASTER_TABLE(CUSTOMER);

ALTER TABLE CUSTOMER_CONTACT_TABLE
ADD CONSTRAINT FK_CUSTOMER_CONTACT_CUSTOMER FOREIGN KEY (CUSTOMER) 
    REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.CUSTOMER_MASTER_TABLE(CUSTOMER);

ALTER TABLE CUSTOMER_MASTER_TABLE
ADD CONSTRAINT FK_CUSTOMER_GROUP FOREIGN KEY (CUSTOMER_GROUP) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.CUSTOMER_GROUP_TABLE(CUSTOMER_GROUP);
ALTER TABLE CUSTOMER_MASTER_TABLE        
ADD CONSTRAINT FK_CUSTOMER_SALES_ORG FOREIGN KEY (SALES_ORGANIZATION) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.SALES_ORGANIZATION_TABLE(SALES_ORGANIZATION);
ALTER TABLE CUSTOMER_MASTER_TABLE
ADD CONSTRAINT FK_CUSTOMER_DIST_CHANNEL FOREIGN KEY (DISTRIBUTION_CHANNEL) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.DISTRIBUTION_CHANNEL_TABLE(DISTRIBUTION_CHANNEL);
ALTER TABLE CUSTOMER_MASTER_TABLE
ADD CONSTRAINT FK_CUSTOMER_DIVISION FOREIGN KEY (DIVISION) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.DIVISION_TABLE(DIVISION);
ALTER TABLE CUSTOMER_MASTER_TABLE
ADD CONSTRAINT FK_CUSTOMER_COUNTRY FOREIGN KEY (COUNTRY) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.COUNTRY_TABLE(COUNTRY);

ALTER TABLE REGION_TABLE
ADD CONSTRAINT FK_REGION_COUNTRY FOREIGN KEY (COUNTRY) 
        REFERENCES SAP_DATA_PRODUCT_CUSTOMER.PUBLIC.COUNTRY_TABLE(COUNTRY);

-- =====================================================================================
-- SALES ORDER DATABASE TABLES
-- =====================================================================================

USE DATABASE SAP_DATA_PRODUCT_SALES_ORDER;
USE SCHEMA PUBLIC;

-- Sales Order Header Table
CREATE OR REPLACE TABLE SALES_ORDER_HEADER_TABLE (
    SALES_ORDER VARCHAR(10) NOT NULL,
    CUSTOMER VARCHAR(10),
    SALES_ORDER_DATE DATE,
    REQUESTED_DELIVERY_DATE DATE,
    TOTAL_NET_AMOUNT NUMBER(15,2),
    TRANSACTION_CURRENCY VARCHAR(3),
    SALES_ORDER_STATUS VARCHAR(20),
    OVERALL_SD_PROCESS_STATUS VARCHAR(20),
    SALES_ORGANIZATION VARCHAR(4),
    DISTRIBUTION_CHANNEL VARCHAR(2),
    DIVISION VARCHAR(2),
    SALES_ORDER_TYPE VARCHAR(2),
    PRIMARY KEY (SALES_ORDER)
);

-- Sales Order Item Table
CREATE OR REPLACE TABLE SALES_ORDER_ITEM_TABLE (
    SALES_ORDER VARCHAR(10) NOT NULL,
    SALES_ORDER_ITEM NUMBER(38,0) NOT NULL,
    MATERIAL VARCHAR(10),
    SALES_ORDER_QUANTITY NUMBER(10,2),
    SALES_ORDER_QUANTITY_UNIT VARCHAR(3),
    NET_AMOUNT NUMBER(15,2),
    PRIMARY KEY (SALES_ORDER, SALES_ORDER_ITEM)
);

-- Customer Table
CREATE OR REPLACE TABLE CUSTOMER_TABLE (
    CUSTOMER VARCHAR(10) NOT NULL,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    COUNTRY VARCHAR(3),
    POSTAL_CODE VARCHAR(10),
    STREET VARCHAR(100),
    REGION VARCHAR(3),
    CUSTOMER_GROUP VARCHAR(2),
    PRIMARY KEY (CUSTOMER)
);

-- Material Table
CREATE OR REPLACE TABLE MATERIAL_TABLE (
    MATERIAL VARCHAR(10) NOT NULL,
    MATERIAL_TYPE VARCHAR(50),
    MATERIAL_DESCRIPTION VARCHAR(200),
    BASE_UNIT VARCHAR(3),
    MATERIAL_GROUP VARCHAR(2),
    PRIMARY KEY (MATERIAL)
);

-- Sales Organization Table
CREATE OR REPLACE TABLE SALES_ORGANIZATION_TABLE (
    SALES_ORGANIZATION VARCHAR(4) NOT NULL,
    SALES_ORGANIZATION_NAME VARCHAR(100),
    COMPANY_CODE VARCHAR(4),
    PRIMARY KEY (SALES_ORGANIZATION)
);

-- Distribution Channel Table
CREATE OR REPLACE TABLE DISTRIBUTION_CHANNEL_TABLE (
    DISTRIBUTION_CHANNEL VARCHAR(2) NOT NULL,
    DISTRIBUTION_CHANNEL_NAME VARCHAR(100),
    PRIMARY KEY (DISTRIBUTION_CHANNEL)
);

-- Division Table
CREATE OR REPLACE TABLE DIVISION_TABLE (
    DIVISION VARCHAR(2) NOT NULL,
    DIVISION_NAME VARCHAR(100),
    PRIMARY KEY (DIVISION)
);

-- Sales Order Type Table
CREATE OR REPLACE TABLE SALES_ORDER_TYPE_TABLE (
    SALES_ORDER_TYPE VARCHAR(2) NOT NULL,
    SALES_ORDER_TYPE_NAME VARCHAR(100),
    PRIMARY KEY (SALES_ORDER_TYPE)
);

-- Customer Group Table
CREATE OR REPLACE TABLE CUSTOMER_GROUP_TABLE (
    CUSTOMER_GROUP VARCHAR(2) NOT NULL,
    CUSTOMER_GROUP_NAME VARCHAR(100),
    PRIMARY KEY (CUSTOMER_GROUP)
);

-- =====================================================================================
-- SHIPPING POINT DATABASE TABLES
-- =====================================================================================

USE DATABASE SAP_DATA_PRODUCT_SSP;
USE SCHEMA PUBLIC;

-- Shipping Point Table
CREATE OR REPLACE TABLE SHIPPING_POINT_TABLE 
CLUSTER BY (shipping_point, language) (
    SHIPPING_POINT VARCHAR(4) NOT NULL,
    SHIPPING_POINT_NAME VARCHAR(100),
    LANGUAGE VARCHAR(2) NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SHIPPING_POINT, LANGUAGE)
);

-- Plant Table
CREATE OR REPLACE TABLE PLANT_TABLE 
CLUSTER BY (plant_key) (
    PLANT_KEY VARCHAR(4) NOT NULL,
    PLANT_NAME VARCHAR(100) NOT NULL,
    PLANT_TYPE VARCHAR(20),
    COUNTRY VARCHAR(3),
    REGION VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Language Table
CREATE OR REPLACE TABLE LANGUAGE_TABLE 
CLUSTER BY (language_key) (
    LANGUAGE_KEY VARCHAR(2) NOT NULL,
    LANGUAGE_NAME VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Shipping Point Master Table
CREATE OR REPLACE TABLE SHIPPING_POINT_MASTER_TABLE 
CLUSTER BY (shipping_point) (
    SHIPPING_POINT VARCHAR(4) NOT NULL,
    SHIPPING_POINT_DESCRIPTION VARCHAR(100),
    PLANT VARCHAR(4),
    STORAGE_LOCATION VARCHAR(4),
    LOADING_GROUP VARCHAR(4),
    SHIPPING_CONDITION VARCHAR(2),
    DELIVERY_PRIORITY VARCHAR(2),
    TRANSPORTATION_GROUP VARCHAR(4),
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SHIPPING_POINT)
);

-- =====================================================================================
-- END OF DDL EXPORT
-- =====================================================================================
-- This file contains all the CREATE statements needed to recreate the three
-- SAP S/4HANA data product databases with their complete table structures.
-- =====================================================================================
